### ISSUE TITLE
[QUESTION] direct connection

### ISSUE THREAD

**Issue by bandycj** [tonesto7/homebridge-smartthings-v2#108]
I noticed the patch notes mention removing direct connections because they don't speed anything up. I'm curious if they help with resiliency though. 

If internet is out wouldn't the direct connection enable homekit control of smartthings devices?

**Comment by tonesto7** [comment]
Unfortunately, No there is no offline communication 😦 

Basically,  Even though it was "local" to the hub it still had to relay to the cloud and wake the smart app.  So, in the end, all it really did was use a generic event endpoint on the hub instead of the specific endpoint for the smart app.

So really we are causing less platform load by just directly targetting the SmartApp endpoint.

**Comment by bandycj** [comment]
Ah, good to know, thanks :)
