### ISSUE TITLE
Work without bridge

### ISSUE THREAD

**Issue by ngrimes08** [tonesto7/homebridge-smartthings-v2#138]
Will this work without a smartthings hub? I have a washer, dryer, and fridge and they are all connected and communicating without a smartthings hub. Would like to get washer and dryer in HomeKit but don’t want to pay for another hub.

**Comment by zburk** [comment]
@ngrimes08 
Just wanted to make sure you saw this in the FAQs

> Q: Can this support Samsung Washers, Dryers, Window AC, Robot Vacuum's? A: Not in the way you hoped. There are no characteristics in Homekit to allow it beyond simple On/Off Switches.

To my understanding, since the hub itself isn't doing any processing, as long as you can access the SmartThings app and install the Homebridge SmartApp, I would guess that it would work as long as you disable everything in the config that tries to directly connect to the hub.

**Comment by tonesto7** [comment]
It does use the hub to send events to the plugin.  (I have a new version in development that uses WebSocket to receive events from ST, but it's not going to be ready to release for a bit)

**Comment by ngrimes08** [comment]
Cool. I’ll hold off from buying a hub then. I want to  be able to flash the lights when the washer/dryer turn off/finish a cycle. I have tried by other means such as IFTTT, but only the washer or dryer was supported, can’t remember which, but they are same series washer and dryer, so if one works the other should too I would think. But also when using IFTTT, it eventually caused my lights to randomly change colors, not sure how that happened but once removed that issue stopped.
