### ISSUE TITLE
(QUESTION) TP Link Kasa Smart-Plugs Support

### ISSUE THREAD

**Issue by acharris76** [tonesto7/homebridge-smartthings-v2#93]
Hi, 

I have successfully added the Smartthings plugin to Homebridge running on a MacMini.
All is functioning perfectly but....

I have used the plugin to add TP Link Kasa smart plugs to home bridge. I used to use a Kasa specific plugin and the smart plugs displayed as power points, but that has been failing recently which is why I switched to this. (Using Smartthings also allowed me to connect the smart plugs and a LightwaveRF light switch to a Harmony Elite remote control.)

With this new plugin, the smart plugs are either showing up as switches or, if the switch was named "xxx light" they are showing up as lights - see attached screen below:

![Screenshot 2020-02-11 at 09 33 24](https://user-images.githubusercontent.com/35410395/74225252-3aa4f400-4cb2-11ea-9721-e20e26584538.jpg)

All three devices are Kasa smartplugs. In fact, the one that is called Joseph's fan used to be displayed as a fan.

Have I done something wrong in the setup of the plugin, or the smart app on the Smartthings App? Is there a way of getting the smartplugs to display as power points?

Thanks in advance for any help!

Anthony

**Comment by tonesto7** [comment]
There are inputs in the smart app to define a device type under HomeKit.  
So select the Kasa plug you want to show as a standard fan under the Define Device Types input.

Adding the power reading to HomeKit is tricky which is why I haven't added support for this. 
Native Home App doesn't support power/energy readings. So there isn't a native characteristic for them which is why i've removed them for the time being.

**Comment by THATDONFC** [comment]
@acharris76 I'm using the Kasa TP-Link plugin and it has worked fine since I started using it. You might want to switch back to that and try to figure out why it isn't working. Going through ST to Homebridge seems redundant when there is a native plugin. Kinda like adding a Hue plugin when Hue is HomeKit compatible. 

Here's my config if it helps you with the TP-Link Plugin:
```json
{
    "platform": "TplinkSmarthome",
    "name": "Kasa TP-Link",
    "devices": [
        "68:FF:7B*"
    ],
    "switchModels": [
        "HS105"
    ]
}
```

**Comment by THATDONFC** [comment]
> There are inputs in the smart app to define a device type under HomeKit.
> So select the Kasa plug you want to show as a standard fan under the Define Device Types input.
> 
> Adding the power reading to HomeKit is tricky which is why I haven't added support for this.
> Native Home App doesn't support power/energy readings. So there isn't a native characteristic for them which is why i've removed them for the time being.

I am seeing power/energy reading being sent from ST to Homebridge. Is there a way to prevent those from being sent for the sake of saving some processing power?

**Comment by tonesto7** [comment]
Under the smart app there is a filtering section which allows you to remove attribute/capabilities from devices before they are sent to Homebridge

**Comment by acharris76** [comment]
Hi, 
Thanks for the replies.
I'm going to give the smart app a try with the plug that is a fan.
As for the other plugs, I'm going to leave them as they are - showing as switches rather than plugs - on the basis that everything is working!
I know what you mean about running this via SmartThings, but the TP Link plugin for me had become so unstable that I'm happier to get it working even with this extra step, rather than not. 
Thanks All!
Anthony
